### ISSUE TITLE
Confusing operand name and resource references in codebase

### ISSUE THREAD

**Issue by jaideepr97** [argoproj-labs/argo-rollouts-manager#1]
The new operator creates a Custom resource with kind "argorollout" which is the representation for the rollouts-controller created on the cluster in response to this resource. However, the resource watched by this controller is also called a "rollout". As a result, users of this operator would see 2 resources, an "argorollout" which is actually for the rollout-controller, and then a "rollout" which is the actual rollout itself, and this can be very confusing for users 

Suggested solution:
- Rename the operand to something like "rollouts-controller" so that it is clear to users at first glance that they would be editing the rollouts-controller and not the rollout itself 

I would also suggest extending this renaming to parts of the operator code, such as function names, their associated comments, log messages etc. This would make it more clear for people working on this project and make it harder to get confused about whether this operator is acting on the rollouts-controller resources or resources for the rollouts themselves  
For example:
- `reconccileRolloutsControllerService` vs `reconcileRolloutsService` (and associated comments and log messages)
- `reconcileRolloutsControllerRole` vs `reconcileRolloutsRole`

**Comment by iam-veeramalla** [comment]
Nice suggestion, Makes total sense :)

**Comment by iam-veeramalla** [comment]
Regarding the below points 
```
    `reconccileRolloutsControllerService` vs `reconcileRolloutsService` (and associated comments and log messages)
    `reconcileRolloutsControllerRole` vs `reconcileRolloutsRole`
```

I don't think we should change the names of these methods as they are correct. We are actually reconciling the Rollouts Role and not Rollouts Controller Role.

**Comment by jaideepr97** [comment]
> Regarding the below points
>
> `reconccileRolloutsControllerService` vs `reconcileRolloutsService` (and associated comments and log messages)
>  `reconcileRolloutsControllerRole` vs `reconcileRolloutsRole`
>     
>   I don't think we should change the names of these methods as they are correct. We are actually reconciling the 
>  Rollouts Role and not Rollouts Controller Role.


The purpose of this role is to reconcile rollouts, but rollouts is a resource though, it wouldn't have a serviceaccount of its own, right?
I just meant that the role is associated to the controller's serviceaccount so we should call the function that

**Comment by jgwest** [comment]
Read through the description and comments, and it appears all issues have been addressed.
