### ISSUE TITLE
Support for namespace scoped install mode 

### ISSUE THREAD

**Issue by jaideepr97** [argoproj-labs/argo-rollouts-manager#4]
At present, it appears this operator would only support cluster-scoped installations of the rollouts-controller. There could be a case made for having the ability to restrict a rollouts-controller to only target rollouts in a specific namespace/namespaces when operating within multi-tenant clusters. This would be especially useful if the rollouts-controller CR supports features like automated analysisRuns etc, which can be enabled/disabled per controller based on the requirements of the tenants of a given namespace

Argo rollouts does have a namespace-install manifest : https://github.com/argoproj/argo-rollouts/blob/master/manifests/namespace-install.yaml

Suggested approach:
- create a rolebinding for the clusterrole to restrict the controller to a specific namespace when installed in namespace-scoped mode 
- provide a mechanism for cluster-admins to elevate a given namespace-scoped rollouts-controller instance to cluster-scoped mode

**Comment by jgwest** [comment]
Superseded by #20
