### ISSUE TITLE
Missing `argo-rollouts-config` cm 

### ISSUE THREAD

**Issue by jaideepr97** [argoproj-labs/argo-rollouts-manager#5]
The operator currently does not create the `argo-rollouts-config` config map at the time of installing the controller and creating required resources. The `argo-rollouts-config` cm is included in the [Argo rollouts install.yaml manifest](https://github.com/argoproj/argo-rollouts/blob/master/manifests/install.yaml#L15077)

We should also make sure to include a controller to reconcile this config map moving forwards

**Comment by jgwest** [comment]
Now that #15 has merged, this is done
